### ISSUE TITLE
Display values on custom key

### ISSUE THREAD

**Issue by Aybee5** [simedia-tech/vue-autosearch#4]
Thank you very much for the package.

I think one feature that can be added to this is to allow a custom key for which to display on the dropdowns. For example, if a have an array of options like this
```
 options: [
          { id: 1, real_name: "Tesla Model S", name: "testlams" },
          { id: 2, real_name: "Tesla Model 3", name:"teslam3" }
        ]
```
I can be able to pass a prop say `lookupKey` to search with. I can look into adding such a feature if you think we should do it.

**Comment by ivansieder** [comment]
Hi @Aybee5, thank you for your input. Unfortunately this package is not being maintained anymore, as it was mostly intended as a temporary workaround as there was no really useful package for Vue 3 at that time. I'd suggest you check out https://github.com/vueform/multiselect, which has tons and tons of useful features!
